version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload in development
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    stdin_open: true
    tty: true